In [19]:
import re

def prepare_txt():
    f = open('data/ArSAS-normalized.txt')
    all_text = open("data/dataset_full.txt", "w")
    speech_act_labels = ['Assertion', 'Recommendation', 'Expression', 'Question', 'Request', 'Miscellaneous']
    sentiment_labels = ['Positive', 'Negative', 'Neutral', 'Mixed']

    count = 0
    check_arr = []
    duplicate = 0

    line = f.readline()
    i = 0
    no_normalized = 0
    while line:
        try:
            line = f.readline()
        except:
            break
        tokens = re.split(r'\t+', line)
        try:
            tweet_id = int(tokens[0].replace('"', ''))
            tweet_30 = tokens[7].replace('"', '').split(" ")[:30]
            tweet_50 = tokens[7].replace('"', '').split(" ")[:50]
        except:
            no_normalized += 1
            continue
        label_sa = speech_act_labels.index(tokens[5].replace('"', ''))
        label_se =  sentiment_labels.index(tokens[3].replace('"', ''))


        if label_sa == 5:
            continue
        if label_se == 3:
            continue
        if tweet_id in check_arr:
            continue
        else:
            check_arr.append(tweet_id)
        all_text.write(line)
        i = i + 1
    all_text.close()
    print("total dataset length ", len(check_arr))
    return


prepare_txt()


total dataset length  18343


In [1]:
import csv, random, re

speech_act_labels = ['Assertion', 'Recommendation', 'Expression', 'Question', 'Request']
sentiment_labels = ['Positive', 'Negative', 'Neutral']

def arr_to_str(arr):
    return ' '.join(t for t in arr).lstrip('"').rstrip('"')


def all_text_field_to_file():
    global speech_act_labels
    f = open('data/dataset_full.txt')
    train_j = open("ArSAS/json/train_final.json", "w")
    test_j = open("ArSAS/json/test_final.json", "w")
    dev_j = open("ArSAS/json/dev_final.json", "w")
    
    train_sa_30 = csv.writer(open("ArSAS/data_sa_30/train.csv", "w+"))
    test_sa_30 = csv.writer(open("ArSAS/data_sa_30/test.csv", "w+"))
    test_sa_30_backup = csv.writer(open("ArSAS/data_sa_30/test_backup.csv", "w+"))
    dev_sa_30 = csv.writer(open("ArSAS/data_sa_30/dev.csv", "w+"))
    
    train_sa_50 = csv.writer(open("ArSAS/data_sa_50/train.csv", "w+"))
    test_sa_50 = csv.writer(open("ArSAS/data_sa_50/test.csv", "w+"))
    test_sa_50_backup = csv.writer(open("ArSAS/data_sa_50/test_backup.csv", "w+"))
    dev_sa_50 = csv.writer(open("ArSAS/data_sa_50/dev.csv", "w+"))


    train_se_30 = csv.writer(open("ArSAS/data_se_30/train.csv", "w+"))
    test_se_30 = csv.writer(open("ArSAS/data_se_30/test.csv", "w+"))
    test_se_30_backup = csv.writer(open("ArSAS/data_se_30/test_backup.csv", "w+"))
    dev_se_30 = csv.writer(open("ArSAS/data_se_30/dev.csv", "w+"))

    train_se_50 = csv.writer(open("ArSAS/data_se_50/train.csv", "w+"))
    test_se_50 = csv.writer(open("ArSAS/data_se_50/test.csv", "w+"))
    test_se_50_backup = csv.writer(open("ArSAS/data_se_50/test_backup.csv", "w+"))
    dev_se_50 = csv.writer(open("ArSAS/data_se_50/dev.csv", "w+"))
    
    test_sa_30.writerow(["id", "sentence"])
    test_sa_50.writerow(["id", "sentence"])
    test_se_30.writerow(["id", "sentence"])
    test_se_50.writerow(["id", "sentence"])

    test_sa_30_backup.writerow(["id", "sentence", "label"])
    test_sa_50_backup.writerow(["id", "sentence", "label"])
    test_se_30_backup.writerow(["id", "sentence", "label"])
    test_se_50_backup.writerow(["id", "sentence", "label"])



    train_count = 0
    dev_count = 0
    test_count = 0

    i = 0
    no_normalized = 0
    lines = f.readlines()
    for line in lines:
        tokens = re.split(r'\t+', line)
        tweet_id = int(tokens[0].replace('"', ''))
        tweet_30 = tokens[7].replace('"', '').split(" ")[:30]
        tweet_50 = tokens[7].replace('"', '').split(" ")[:50]
        label_sa = speech_act_labels.index(tokens[5].replace('"', '')),
        label_se = sentiment_labels.index(tokens[3].replace('"', ''))            

        ob = {
            'tweet_id': tweet_id,
            'tweet_30': tweet_30,
            'tweet_50': tweet_50,
            'label_sa': speech_act_labels.index(tokens[5].replace('"', '')),
            'label_se': sentiment_labels.index(tokens[3].replace('"', ''))            
        }

        rand = random.random()
        if rand > 0.4:
            train_j.write(str(ob).replace("\'", "\"") + '\n')
            train_sa_30.writerow([ob['tweet_id'], ob['label_sa'], "a", arr_to_str(ob['tweet_30'])])
            train_sa_50.writerow([ob['tweet_id'], ob['label_sa'], "a", arr_to_str(ob['tweet_50'])])
            train_se_30.writerow([ob['tweet_id'], ob['label_se'], "a", arr_to_str(ob['tweet_30'])])
            train_se_50.writerow([ob['tweet_id'], ob['label_se'], "a", arr_to_str(ob['tweet_50'])])
            train_count += 1
        else:
            if 0<rand<=0.2:
                dev_j.write(str(ob).replace("\'", "\"") + '\n')
                dev_sa_30.writerow([ob['tweet_id'], ob['label_sa'], "a", arr_to_str(ob['tweet_30'])])
                dev_sa_50.writerow([ob['tweet_id'], ob['label_sa'], "a", arr_to_str(ob['tweet_50'])])
                dev_se_30.writerow([ob['tweet_id'], ob['label_se'], "a", arr_to_str(ob['tweet_30'])])
                dev_se_50.writerow([ob['tweet_id'], ob['label_se'], "a", arr_to_str(ob['tweet_50'])])
                dev_count += 1
            else:
                test_j.write(str(ob).replace("\'", "\"") + '\n')
                test_sa_30.writerow([ob['tweet_id'], arr_to_str(ob['tweet_30'])])
                test_sa_50.writerow([ob['tweet_id'], arr_to_str(ob['tweet_50'])])
                test_se_30.writerow([ob['tweet_id'], arr_to_str(ob['tweet_30'])])
                test_se_50.writerow([ob['tweet_id'], arr_to_str(ob['tweet_50'])])
                
                test_sa_30_backup.writerow([ob['tweet_id'], arr_to_str(ob['tweet_30']), ob['label_sa']])
                test_sa_50_backup.writerow([ob['tweet_id'], arr_to_str(ob['tweet_50']), ob['label_sa']])
                test_se_30_backup.writerow([ob['tweet_id'], arr_to_str(ob['tweet_30']), ob['label_se']])
                test_se_50_backup.writerow([ob['tweet_id'], arr_to_str(ob['tweet_50']), ob['label_se']])
                test_count += 1
        i = i + 1
    train_j.close()
    test_j.close()
    dev_j.close()


    print("line count ", i)
    print("no normalized ", no_normalized)
    print("train ", train_count)
    print("dev ", dev_count)
    print("test ", test_count)

    
all_text_field_to_file()




line count  18343
no normalized  0
train  11064
dev  3573
test  3706


In [2]:
import pandas as pd
data_type = ['train', 'dev', 'test']
labels = ['sa', 'se']
numbers = ['30', '50']


for i in data_type:
    for j in labels:
        for k in numbers:
            df = pd.read_csv('ArSAS/data' + '_' + j + '_' + k + '/' +  i + '.csv')
            if 'test' in i:
                df.to_csv('ArSAS/data' + '_' + j + '_' + k + '/' +  i + '.tsv', sep='\t', index=False, header=True)
                df = pd.read_csv('ArSAS/data' + '_' + j + '_' + k + '/' +  i + '_backup.csv')
                df.to_csv('ArSAS/data' + '_' + j + '_' + k + '/' +  i + '_backup.tsv', sep='\t', index=False, header=True)
            else:
                df.to_csv('ArSAS/data' + '_' + j + '_' + k + '/' +  i + '.tsv', sep='\t', index=False, header=False)

print("done")          

done


In [61]:
import csv, random, xlwt

def create_switchboard_dataset():

    speech_act_labels = []
    speech_act_labels_count = []

    train_count = 0
    dev_count = 0
    test_count = 0
    
    wb = xlwt.Workbook()
    ws = wb.add_sheet('Sheet1')
    row_count = 0
    ws.write(row_count, 0, "Category")
    ws.write(row_count, 1, "Count")
    row_count += 1

    with open('data/switchboard_complete.csv', newline='') as f:
        reader = csv.reader(f)
        for i, row in enumerate(reader):
            if i == 0:
                continue
            sa_label = row[5]
                
            if sa_label not in speech_act_labels:
                speech_act_labels.append(sa_label)
                speech_act_labels_count.append(0)
            label = speech_act_labels.index(sa_label)
            speech_act_labels_count[label] += 1
    speech_act_labels_final = [x for _,x in sorted(zip(speech_act_labels_count,speech_act_labels), reverse=True)]
    speech_act_labels_count_final = [x for x,_ in sorted(zip(speech_act_labels_count,speech_act_labels), reverse=True)]


    for i in range(len(speech_act_labels)):
        print(speech_act_labels_final[i], speech_act_labels_count_final[i])
        ws.write(i+1, 0, speech_act_labels_final[i])
        ws.write(i+1, 1, speech_act_labels_count_final[i])

    wb.save("Switchboard_Summary.xlsx")


    print(len(speech_act_labels_final))
    print(len(speech_act_labels_count_final))
    
    
create_switchboard_dataset()

Forward-Communicative-Function:Statement:Statement-non-opinion 72365
Backwards-Communicative-Function:Understanding:Acknowledge 37500
Forward-Communicative-Function:Statement:Statement-opinion 25263
Other:Segment-(multi-utterance) 18352
Communicative-Status:Uninterpretable 15279
Backwards-Communicative-Function:Agreement:Accept 10933
Info-request:Yes-No-Question 5623
Backwards-Communicative-Function:Understanding:Appreciation 4586
none 3357
Info-request:Yes answers 2970
Other-forward-function:Conventional-closing 2524
Info-request:Wh-Question 1946
Communicative-Status:Non-verbal 1891
Backwards-Communicative-Function:Answer:No answers 1350
Backwards-Communicative-Function:Understanding:Response Acknowledgement 1291
Other:Hedge 1194
Other 1135
Backwards-Communicative-Function:Understanding:Backchannel-in-question-form 1035
Backwards-Communicative-Function:Understanding:Summarize/reformulate 928
Backwards-Communicative-Function:Answer:Affirmative-non-yes-answers 839
Info-request:Action-di

In [5]:
import json
import numpy as np

speech_act_labels = ['Assertion', 'Recommendation', 'Expression', 'Question', 'Request', 'Miscellaneous']
sentiment_labels = ['Positive', 'Negative', 'Neutral', 'Mixed']
arr = np.zeros(shape=(5,3))
fox = np.zeros(shape=(5,3))
cats = np.zeros(5)
f = open("data/train_final.json")
while True:
    try:
        line = f.readline()
    except:
        break
    x = line.split(",")
    try:
        label_sa = int(x[-2].split(':')[1])
        label_se = int(x[-1].split(':')[1][:-2])
        arr[label_sa][label_se] += 1
        cats[label_sa] += 1
    except:
        break
print(arr)
for i, elem in enumerate(arr):
    for j, value in enumerate(elem):
        fox[i][j] = value / sum(elem) * 100
print(fox)
print(cats)

[[ 573.  278. 3826.]
 [  18.   20.   12.]
 [2006. 3828.  158.]
 [  25.  224.  147.]
 [  36.   42.   21.]]
[[12.25144323  5.94398118 81.80457558]
 [36.         40.         24.        ]
 [33.47797063 63.88518024  2.63684913]
 [ 6.31313131 56.56565657 37.12121212]
 [36.36363636 42.42424242 21.21212121]]
[4677.   50. 5992.  396.   99.]


In [11]:
import statistics

arr = [1480, 15, 2007, 123, 26]
performance = [0.81, 0 , 0.82, 0.39, 0.23]
sum_p = 0
for i, elem in enumerate(performance):
    sum_p += elem * arr[i] / sum(arr)
print(statistics.mean(performance))
print(sum_p)

0.45
0.7938893453848261


In [25]:
import statistics

arr = [883, 1428, 1340]
perfor = [[0.59, 0.78, 0.76], [0.58, 0.78, 0.75], [0.56, 0.75, 0.76], [0.59, 0.80, 0.78],
               [0.57, 0.74, 0.74], [0.58, 0.76, 0.74]]
for i, elem in enumerate(perfor):
    sum_p = 0
    for j, val in enumerate(elem):
        sum_p += val * arr[j] / sum(arr)
    print('& %.2f' %statistics.mean(elem), '& %.2f' %sum_p)


& 0.71 & 0.73
& 0.70 & 0.72
& 0.69 & 0.71
& 0.72 & 0.74
& 0.68 & 0.70
& 0.69 & 0.71


In [35]:
import csv
import numpy as np

np.set_printoptions(suppress=True)
arr = np.zeros(54)
f = open("switchboard_data/switchboard/train.tsv")
x = csv.reader(f, delimiter = '\t')
for row in x:
    arr[int(row[1])] += 1
print(arr)
l_50 = 0
for elem in arr:
    if elem < 50:
        l_50 += 1
print("Support less than 50 ", l_50)

[  929.  1539.  4521. 14757. 57847.   566.   956.  8715. 29974. 20241.
  1013.  1082.   680.   799.  2381.  1486. 12121.  3685.   730.   535.
   107.   449.  2702.   220.    83.   509.   442.   162.    54.   194.
   224.    38.    16.    90.  2007.    59.   275.    86.   235.    48.
    63.   183.    29.    59.   131.    18.     5.     7.    32.    11.
     4.     5.     4.     7.]
Support less than 50  13


In [42]:
import csv
a = open('ArSAS/data_se_30/test.tsv')
reader_a = csv.reader(a, delimiter='\t')
for i, row_a in enumerate(reader_a):
    print(i, row_a)

0 ['id', 'sentence']
1 ['929755693011427331', 'اهداف مباراه غانا NUM مصر NUM تصفيات كاس العالم NUM روسيا GHA NUM vs NUM EYG URL\n']
2 ['928645180873469953', 'HASH قاعه المؤتمرات بشرم الشيخ URL\n']
3 ['929607749461250048', 'بسم الله نبدا نغرد علي وسم HASH تحقيق اهداف ثوره يناير العيش والحريه والعداله الاجتماعيه والكرامه الانسانيه HASH URL\n']
4 ['928881721738752000', 'فيديو هدف مباراه سويسرا NUM NUM ايرلندا ش NUM تصفيات كاس العالم URL\n']
5 ['930176439529496576', 'دوله HASH تفتح تحقيقا لكشف حقيقه معلومات عن محاوله التلاعب بعملتها في الايام الاولي ل HASH NUM HASH URL\n']
6 ['927551566885937152', 'قناه فرانس NUM قراءه في صحف الخليج ولي العهد السعودي يسعي لاحكام قبضته قبل تتويجه ملكا عبر نبض URL\n']
7 ['931983476835995648', 'ياعم يا عسكري ماهينور دي عملت ايه عامل عليها دكر ماتشوف سعاده البيه هي الرجوله كده احيه يا شيخ احيه HASH مصريه HASH URL\n']
8 ['929817438354657280', 'بعد مقاطعه قطر لم يفتيء يسب الحكومات المتسلطه وغض الطرف عن كل مايمت لقطر المحاصره حسب رايه وكانها واحه الديموقراطيه وال

1309 ['932011991908192256', 'الحمدلله والله يبارك فيك اللي عنده محمد صلاح ما ينخاف عليه\n']
1310 ['930956910110625793', 'من افضل مدافع في المنتخب السعودي خلال تصفيات كاس العالم NUM اسامه هوساوي ريتويت NUM عمر هوساوي اعجاب صاحب الطلب URL\n']
1311 ['930612144596553729', 'عاجل وبالتفاصيل اعترافات الارهابي الذي تحدث عنه السيسي منفذ حادث الواحات اسرار خطيره علق تم ليصلك الاخبار NUM URL\n']
1312 ['928211521603231744', 'وزير الخارجيه عادل الجبير قضيه HASH صغيره جدا ولا تمثل ازمه والدول الاربعه المقاطعه للدوحه لا ترغب في تغيير النظام لكنها تريد تغيير السلوك NUM HASH URL\n']
1313 ['931889448241033216', 'الصديق لؤي الشريف قبيل بدء جلسه يتحدث فيها حول الاختلافات الثقافيه ودورها في الصراع والسلم بين الشعوب في HASH URL\n']
1314 ['930093472526282757', 'محمد صلاح اساسيا مع روما امام كاربي بالدوري الايطالي NUM URL HASH\n']
1315 ['929506527899209729', 'تامر امين يكشف كذب نهي عبد الكريم بعد انسحابها من منتدي شباب العالم فيديو URL\n']
1316 ['930349787194544128', 'HASH عشان زاد الضغط علي حزب الله ايران تب

2189 ['929730716480494976', 'المغرب هو المنتخب الوحيد في العالم الذي لم تتلقي شباكه اي هدف طوال تصفيات كاس العالم NUM حتي الان URL\n']
2190 ['931530026998168960', 'وهل نفعت قضيه تيران وصنافير وهل هناك قضاء سيقبلها ولا يشعر بالحرج او سيبت فيها ايجابيا\n']
2191 ['929095353516875776', 'مبرروك يا مصر منتدي شباب العالم شيء مشرف ويفرح انا مصري وافتخر تحيه اللجنه المنظمه وشباب مصر الواعد المتحضر والمثقف والواعي وتحيا مصر ام الدنيا نلتقي العام القادم باذن الله']
2192 ['926936428709326848', 'HASH اليمن مقاطعه قطر التضييق علي ايران مكافحه فساد ضرب ارهاب وفي ودول لو يتهاوشون اثنين وقف حالها HASH URL\n']
2193 ['929155293669359616', 'مرتضي منصور يفتح النار علي منافسيه بانتخابات الزمالك URL\n']
2194 ['930911773665964032', 'الي اعداء HASH من جلب الدمار والخراب الي بلداننا بعد الثورات ليس الذين ثاروا من اجل الحريه بل الذين لا يريدون للشعوب ان تعيش بحريه HASH\n']
2195 ['929041120847207936', 'تصفيات كاس العالم للرجال في كره السله لبنان يقابل الهند في اولي مبارياته URL\n']
2196 ['927875568531423233', 'نر

2875 ['929262430051618816', 'كل الامنيات للاشقاء العرب الافارقه في تصفيات كاس العالم NUM\n']
2876 ['932213143165722624', 'مصر فايف صلاح يواصل هوايته المفضله ويكسر مزيد من الارقام القياسيه URL\n']
2877 ['929756906155118596', 'شوفت محمد صلاح قلبي دق NUM دقات o lt\n']
2878 ['931912743585767424', 'هو الاعلام لامؤاخذه مش هيستضيف العيال الوحشين بتوع علم ال ولا التانيين المجرمين بتوع تيران وصنافير ولا المعارضين اللي فالسجون ولا هو اعلام تخصص ارهاب\n']
2879 ['930455668540297216', 'HASH HASH الشبابيه بقلم د NUM HASH التفاصيل URL\n']
2880 ['927815125146460160', 'lt img src gt بدءت منذ قليل فعاليات منتدي شباب العالم بمدينه شرم الشيخ بمشاركه مجموعه كبيره من الشباب حول NUM URL\n']
2881 ['928896529183756288', 'lt img src gt احتل نشاط الرئيس عبد الفتاح السيسي عناوين الصحف القوميه الصادره اليوم الجمعه وكذلك اهتمت الصحف NUM URL\n']
2882 ['929391599385234944', 'الحاجه الوحيده اللي حبيتها في البلد دي اكتر من الزمالك هي ثوره يناير المجيده\n']
2883 ['928697766565511173', 'رسميا افضل تشكيله في تصفيات الموند

In [34]:
import csv, random, xlwt

def check_switchboard_file():

    speech_labels_short = []
    speech_labels_big = []
    file_names = []
    
    check_label = ['o','fo','bc','by','fw']


    with open('data/switchboard_complete.csv', newline='') as f:
        reader = csv.reader(f)
        for i, row in enumerate(reader):
            if i == 0:
                continue
            file_name = row[0]
            speech_short = row[4].split(',')
            if len(speech_short) > 1:
                print(speech_short)
            speech_b = row[5]
#             if '3756' not in file_name:
#                 continue
            

            for speech_s in speech_short:
                if speech_s not in speech_labels_short:
                    speech_labels_short.append(speech_s)
#                     if speech_s in check_label:
#                         print(speech_s, speech_b)
#                     if 'am' in speech_s:
#                         print("am in speech label", speech_b)


            if speech_b not in speech_labels_big:
                speech_labels_big.append(speech_b)
#             if speech_b == 'none':
#                 print(file_name)
#                 print(row[11])
#                 break
            if file_name not in file_names:
                file_names.append(file_name)
    print("#labels short ", len(speech_labels_short))
#     if 'aap' in speech_labels_short:
#         print("aap in speech label")
#     if 'am' in speech_labels_short:
#         print("am in speech label")
#     for label in speech_labels_short:
#         print(label)
    print("#labels big ", len(speech_labels_big))
    print("#file names ", len(file_names))
    
            
check_switchboard_file()

['aa', 'ar']
['h', 'sd']
['sv', 'sd', 'o@']
['sd', 'o@']
['bh', 'sd', 'o@']
['aa', 'o@']
['aa^r', 'o@']
['sd', 'o@']
['ng^r', 'o@']
['sd', 'o@']
['sd', 'sv']
['sd', 'o@']
['ad', 'qy@']
['sv', 'o@']
['ad', 'o@']
['sd', 'o@']
['%', 'o@']
['sd', 'o@']
['sd', 'o@']
['sd', 'o@']
['sv', 'o@']
['na', 'sd', 'o@']
['sd', 'o@']
['bk', 'sd', 'o@']
['sv', 'sd', 'o@']
['sd', 'o@']
['fc', 'o@']
['sv', 'o@']
['sv', 'o@']
['sd', 'o@']
['sv', 'sd', 'o@']
['sv', 'o@']
['b^m', 'sd', 'o@']
['sv', 'qy^g@']
['sv', 'o@']
['sv', 'o@']
['aa', 'o@']
['qy', 'am', 'o@']
['br', 'o@']
['sd', 'o@']
['sd', 'o@']
['sv', 'o@']
['sd', 'o@']
['sd', 'o@']
['bf', 'nn', 'o@']
['sd', 'o@']
['sd', 'qy^g']
['ba', 'fe']
#labels short  280
#labels big  54
#file names  1126


In [39]:
import csv, random, xlwt

def check_switchboard_file():

    speech_labels_short = []
    speech_labels_big = []
    file_names = []
    
    check_label = ['o','fo','bc','by','fw']


    with open('data/switchboard_complete.csv', newline='') as f:
        reader = csv.reader(f)
        for i, row in enumerate(reader):
            if i == 0:
                continue
            file_name = row[0]
            speech_s = row[4]
            speech_b = row[5]
            
#             if speech_b == 'none':
#                 print(speech_b, speech_s, file_name, i)
            if speech_b == '':
                print("empty", speech_s, file_name, i)
                
            if speech_s not in speech_labels_short:
                speech_labels_short.append(speech_s)


            if speech_b not in speech_labels_big:
                speech_labels_big.append(speech_b)
#             if speech_b == 'none':
#                 print(file_name)
#                 print(row[11])
#                 break
            if file_name not in file_names:
                file_names.append(file_name)
    print("#labels short ", len(speech_labels_short))
#     if 'aap' in speech_labels_short:
#         print("aap in speech label")
#     if 'am' in speech_labels_short:
#         print("am in speech label")
#     for label in speech_labels_short:
#         print(label)
    print("#labels big ", len(speech_labels_big))
    print("#file names ", len(file_names))
    
            
check_switchboard_file()

empty sd(^q)^t sw01utt/sw_0117_2837.utt 17834
empty sd(^q)^t sw01utt/sw_0123_3186.utt 18736
empty sd(^q)^t sw01utt/sw_0157_3304.utt 24769
empty sd(^q)^t sw01utt/sw_0184_3171.utt 29415
empty sd(^q)^t sw02utt/sw_0231_3150.utt 38465
empty sd(^q)^t sw03utt/sw_0352_3236.utt 61840
empty sd(^q)^t sw04utt/sw_0491_3256.utt 88500
empty sd(^q)* sw05utt/sw_0515_4184.utt 91962
empty sd(^q)* sw05utt/sw_0522_2072.utt 93404
empty sd(^q)^t sw05utt/sw_0526_2160.utt 94023
empty sd(^q)^t sw05utt/sw_0538_2545.utt 96993
empty sd(^q)^t sw05utt/sw_0562_3443.utt 101994
empty sd(^q)^t sw06utt/sw_0639_2187.utt 117044
empty sd(^q)^t sw06utt/sw_0639_2187.utt 117053
empty sv,sd,o@ sw07utt/sw_0701_2631.utt 129778
empty bh,sd,o@ sw07utt/sw_0701_2631.utt 129890
empty na,sd,o@ sw07utt/sw_0710_2996.utt 131876
empty bk,sd,o@ sw07utt/sw_0710_2996.utt 131903
empty sv,sd,o@ sw07utt/sw_0712_3029.utt 132271
empty sv,sd,o@ sw07utt/sw_0716_3105.utt 133196
empty sd(^q)^t sw07utt/sw_0717_3384.utt 133354
empty b^m,sd,o@ sw07utt/sw

In [95]:
import xlrd, os, xlwt
from openpyxl import Workbook, load_workbook

# THIS_FOLDER = os.path.dirname(os.path.abspath(__file__))
# my_file_1 = os.path.join(THIS_FOLDER, 'rudra_speech_act_sentiment.xlsx')

workbook_1 = xlrd.open_workbook('rudra_speech_act_sentiment.xlsx')
worksheet_1 = workbook_1.sheet_by_name('SW_updated')

speech_act_b = {}
speech_act_s = {}
valid_exp_count = 0

wb = Workbook()
ws = wb.worksheets[0]
row_count = 1
ws.cell(row=row_count, column=1).value = "Index"
ws.cell(row=row_count, column=2).value = "File_name"
ws.cell(row=row_count, column=3).value = "Utterance"
ws.cell(row=row_count, column=4).value = "Dialog_act_big"
ws.cell(row=row_count, column=5).value = "Dialog_act_small"


row_count += 1


for i in range(worksheet_1.nrows):
    if i == 0:
        continue
    category = worksheet_1.cell(i,0).value
    labels = worksheet_1.cell(i, 1).value.split(",")
    for label in labels:
        speech_act_s[label] = {'category': category, 'count': 0}
        if category not in speech_act_b:
            speech_act_b[category] = 0
    

with open('data/switchboard_complete.csv', newline='') as f:
    reader = csv.reader(f)
    for i, row in enumerate(reader):
        if i == 0:
            continue
        file_name = row[0]
        speech_s = row[4].split(",")
        for s_s in speech_s:
            if s_s in speech_act:
                speech_act_s[s_s]['count'] += 1
                ws.cell(row=row_count, column=1).value = row_count
                ws.cell(row=row_count, column=2).value = file_name
                ws.cell(row=row_count, column=3).value = row[11]
                ws.cell(row=row_count, column=4).value = speech_act_s[s_s]['category']
                ws.cell(row=row_count, column=5).value = s_s


#                 ws.write(row_count, 0, row_count)
#                 ws.write(row_count, 1, file_name)
#                 ws.write(row_count, 2, row[11])
#                 ws.write(row_count, 3, speech_act_s[s_s]['category'])
#                 ws.write(row_count, 4, s_s)
                row_count += 1
                break



    
for key in speech_act_s:
    print(key, ",", speech_act_s[key])
print(".......")

mypath = 'swb1_dialogact_annot/sw13utt/'
onlyfiles = [f for f in listdir(mypath) if isfile(join(mypath, f))]

un_text = '============'
remove_text = ['<Laughter>', '<laughter>', '<Throat_clearing>', '<throat_clearing>']


for f_name in onlyfiles:
    file_name = 'swb1_dialogact_annot/sw13utt/' + f_name
    file_ob = open(file_name, 'r')
    lines = file_ob.readlines()
    index = 0
    for i, line in enumerate(lines):
        if un_text in line:
            index = i
            lines = lines[index + 3:]
            break
    for line in lines:
        line_f = line.split(":")
        if len(line_f) == 2:
            speech_s = line_f[0].split(" ")[0]
            text = line_f[1].strip()[:-1]
            for r_text in remove_text:
                if r_text in text:
                    text = text.replace(r_text, '')
            for s_s in speech_s.split(","):
                if s_s in speech_act:
                    speech_act_s[s_s]['count'] += 1
                    ws.cell(row=row_count, column=1).value = row_count
                    ws.cell(row=row_count, column=2).value = 'sw13utt/' + f_name
                    ws.cell(row=row_count, column=3).value = text
                    ws.cell(row=row_count, column=4).value = speech_act_s[s_s]['category']
                    ws.cell(row=row_count, column=5).value = s_s


#                     ws.write(row_count, 0, row_count)
#                     ws.write(row_count, 1, 'sw13utt/' + f_name)
#                     ws.write(row_count, 2, text)
#                     ws.write(row_count, 3, speech_act_s[s_s]['category'])
#                     ws.write(row_count, 4, s_s)
                    row_count += 1
                    break



for key in speech_act_s:
    speech_act_b[speech_act_s[key]['category']] += speech_act_s[key]['count']

print("NEW FILE ADDED ////////")
for key in speech_act_s:
    print(key, ",", speech_act_s[key])
print(".......")
for key in speech_act_b:
    print(key, ",", speech_act_b[key])
    valid_exp_count += speech_act_b[key]


print(".......")

print("valid #examples ", valid_exp_count)
print("valid #categories", len(speech_act_b))

wb.save("switchboard_data/Switchboard_new.xlsx")




sd , {'category': 'Statement-non-opinion', 'count': 68859}
b , {'category': 'Acknowledge (Backchannel)', 'count': 35446}
sv , {'category': 'Statement-opinion', 'count': 24768}
fx , {'category': 'Statement-opinion', 'count': 9}
aa , {'category': 'Agree/Accept', 'count': 9928}
% - , {'category': 'Abandoned or Turn-Exit', 'count': 0}
ba , {'category': 'Appreciation', 'count': 4451}
fe , {'category': 'Appreciation', 'count': 131}
qy , {'category': 'Yes-No-Question', 'count': 3720}
qr , {'category': 'Yes-No-Question', 'count': 212}
x , {'category': 'Non-verbal', 'count': 1843}
ny , {'category': 'Yes answers', 'count': 2764}
fc , {'category': 'Conventional-closing', 'count': 2344}
% , {'category': 'Uninterpretable', 'count': 15145}
qw , {'category': 'Wh-Question', 'count': 1851}
nn , {'category': 'No answers', 'count': 1205}
bk , {'category': 'Response Acknowledgement', 'count': 1239}
h , {'category': 'Hedge', 'count': 1186}
qy^d , {'category': 'Declarative Yes-No-Question', 'count': 1180}
o

In [84]:
dir_name = ['00', '01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13']
all_files = []
file_count = 0
for d_name in dir_name:
    
    mypath = 'swb1_dialogact_annot/sw' + d_name + 'utt'
    onlyfiles = [f for f in listdir(mypath) if isfile(join(mypath, f))]
    file_count += len(onlyfiles)

print("# files ", file_count)

# files  1157


In [88]:
with open('data/switchboard_complete.csv', newline='') as f:
    reader = csv.reader(f)
    for i, row in enumerate(reader):
        if i == 0:
            continue
        file_name = row[0]
        speech_s = row[4].split(",")
        speech_b = row[5]
        if row[5] == '':
            print(row[4], row[5], file_name)
            


sd(^q)^t  sw01utt/sw_0117_2837.utt
sd(^q)^t  sw01utt/sw_0123_3186.utt
sd(^q)^t  sw01utt/sw_0157_3304.utt
sd(^q)^t  sw01utt/sw_0184_3171.utt
sd(^q)^t  sw02utt/sw_0231_3150.utt
sd(^q)^t  sw03utt/sw_0352_3236.utt
sd(^q)^t  sw04utt/sw_0491_3256.utt
sd(^q)*  sw05utt/sw_0515_4184.utt
sd(^q)*  sw05utt/sw_0522_2072.utt
sd(^q)^t  sw05utt/sw_0526_2160.utt
sd(^q)^t  sw05utt/sw_0538_2545.utt
sd(^q)^t  sw05utt/sw_0562_3443.utt
sd(^q)^t  sw06utt/sw_0639_2187.utt
sd(^q)^t  sw06utt/sw_0639_2187.utt
sv,sd,o@  sw07utt/sw_0701_2631.utt
bh,sd,o@  sw07utt/sw_0701_2631.utt
na,sd,o@  sw07utt/sw_0710_2996.utt
bk,sd,o@  sw07utt/sw_0710_2996.utt
sv,sd,o@  sw07utt/sw_0712_3029.utt
sv,sd,o@  sw07utt/sw_0716_3105.utt
sd(^q)^t  sw07utt/sw_0717_3384.utt
b^m,sd,o@  sw07utt/sw_0721_3777.utt
qy,am,o@  sw07utt/sw_0733_4940.utt
sd(^q)^t  sw07utt/sw_0737_2110.utt
sd(^q)^t  sw07utt/sw_0737_2110.utt
sd(^q)^t  sw07utt/sw_0737_2110.utt
sd(^q)^t  sw07utt/sw_0737_2110.utt
sd(^q)*  sw07utt/sw_0739_2180.utt
bf,nn,o@  sw07utt/sw_0